# Generated by Django 5.2.10 on 2026-03-02 23:49

import django.db.models.deletion
import manager.models
import manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_code", models.CharField(max_length=32, unique=True)),
                ("file_obj", models.FileField(upload_to=manager.utils.get_hash_path)),
                ("size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShareItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "expire_at",
                    models.DateTimeField(default=manager.models.default_expire_at),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="manager.filecontent",
                    ),
                ),
            ],
        ),
    ]
