# Generated by Django 5.2.10 on 2026-03-15 08:17

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecontent",
            name="retention_until",
            field=models.DateTimeField(default=manager.models.default_file_expire_at),
        ),
    ]
